#!/usr/bin/env python3
import argparse
from client.upload_file import upload_file
from client.udp_file_upload import UDPFileUpload
from client.tcp_file_upload import TCPFileUpload

def parse_arguments():
    parser = argparse.ArgumentParser()

    parser.add_argument("-H", "--server-host", default="127.0.0.1", help="la dirección IP del servidor")
    parser.add_argument("-P", "--server-port", type=int, default=8080, help="el puerto del servidor")
    parser.add_argument("-s", "--src", help="path del archivo a enviar al servidor", required=True)
    parser.add_argument("-n", "--name", help="el nombre que tomará el archivo en el servidor", required=True)
    parser.add_argument("-p", "--protocol", help="el protocolo a utilizar para la comunicación",
                        default="tcp", choices=['tcp', 'udp'])

    return parser.parse_args()


def main():
    args = parse_arguments()
    server_address = (args.server_host, args.server_port)

    if args.protocol == "tcp":
        upload_file(server_address, args.src, args.name, TCPFileUpload)
    elif args.protocol == "udp":
        upload_file(server_address, args.src, args.name, UDPFileUpload)
    else:
        raise Exception("protocolo invalido")


main()
